USE bank_db;

SHOW FULL TABLES FROM bank_db;
SHOW TABLES;
SHOW COLUMNS FROM c053;

CREATE TABLE c053 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

DROP TABLE c053;

ALTER TABLE c053
    ADD COLUMN surname1 VARCHAR(50) NOT NULL;

SELECT * FROM c053;
