package cl.praxis.university.applicationjava;

import java.util.ArrayList;
import java.util.List;

public class Repositorio {
    List<Entidad> entidades = new ArrayList<>();

    public Repositorio() {
        entidades.add(new Entidad(1, "Martha", "Akehurst", 5.6, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(2, "Emmett", "Pehrsson", 6.5, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(2, "Emmett", "Pehrsson", 4.4, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(5, "Dewain", "Griffithe", 4.7, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(5, "Dewain", "Griffithe", 4.7, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(6, "Andre", "Corneille", 4.5, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(7, "Norton", "Madle", 2.9, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(9, "Angele", "Diament", 1.1, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(9, "Angele", "Diament", 3.5, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(12, "Vinny", "Evins", 5.9, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(12, "Vinny", "Evins", 5.8, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(12, "Vinny", "Evins", 5.8, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(14, "Erin", "Colles", 3.8, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(17, "Magdalene", "Scales", 4.0, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(18, "Alis", "Marquese", 3.2, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(18, "Alis", "Marquese", 4.7, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(20, "Bart", "Gulliford", 3.5, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(21, "Darsie", "Digman", 4.5, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(21, "Darsie", "Digman", 3.4, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(22, "Val", "Bossom", 4.2, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(25, "Herman", "Bradder", 4.6, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(26, "Dicky", "Gabitis", 2.8, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(27, "Isobel", "Jamblin", 5.4, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(28, "Adiana", "Spender", 5.3, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(29, "Emlyn", "Cunnell", 3.1, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(29, "Emlyn", "Cunnell", 3.1, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(31, "Heidi", "MacLeese", 3.0, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(32, "Timmy", "Cason", 3.5, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(33, "Maryl", "Garraway", 4.5, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(33, "Maryl", "Garraway", 3.8, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(33, "Maryl", "Garraway", 3.9, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(34, "Peri", "Mingus", 4.9, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(35, "Cammi", "Mintrim", 5.2, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(36, "Anastassia", "Vockins", 3.7, "Javascript de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(36, "Anastassia", "Vockins", 2.1, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(38, "Bronson", "Trank", 2.4, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(39, "Agace", "Veart", 2.6, "Python de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(40, "Maggie", "Galilee", 1.8, "Sql de 0 a Experto", 1, "Informática"));
        entidades.add(new Entidad(41, "Pierson", "Hartwell", 3.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(42, "Bernardina", "McGowing", 4.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(42, "Bernardina", "McGowing", 5.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(43, "Geoffrey", "Binham", 2.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(44, "Gerri", "Summergill", 3.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 3.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 4.5, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 4.6, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(46, "Vincenz", "Comins", 4.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(47, "Gelya", "Haryngton", 2.5, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(47, "Gelya", "Haryngton", 3.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(48, "Misty", "Haquin", 4.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(49, "Ariana", "Hallgate", 3.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(49, "Ariana", "Hallgate", 5.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(50, "Ayn", "Ryder", 1.1, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(50, "Ayn", "Ryder", 2.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(53, "Bellina", "Bortol", 4.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(53, "Bellina", "Bortol", 5.1, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(54, "Aldin", "Haigh", 3.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(55, "Rois", "Slocum", 4.5, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(55, "Rois", "Slocum", 4.2, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(56, "Juanita", "Clapshaw", 3.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(57, "Hedwiga", "Champniss", 4.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(58, "Zaria", "Cleeves", 3.2, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(58, "Zaria", "Cleeves", 4.4, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(59, "Wandie", "Alonso", 5.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 5.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 4.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 2.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(61, "Karmen", "Levis", 4.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(61, "Karmen", "Levis", 2.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(62, "Rhys", "Kenyon", 2.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(62, "Rhys", "Kenyon", 3.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 3.2, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 4.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 4.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(64, "Gae", "Dellenbrook", 2.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(64, "Gae", "Dellenbrook", 3.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 4.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 2.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 4.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 5.1, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 3.3, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 4.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 1.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 3.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 4.3, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(68, "Alena", "Puttergill", 6.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(68, "Alena", "Puttergill", 5.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(69, "Corrina", "Gogay", 3.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(70, "Fianna", "Tabb", 4.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(71, "Marcile", "Dudden", 5.6, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(72, "Becca", "Pirot", 4.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(74, "Floris", "Dmtrovic", 4.7, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(75, "Hana", "Ramsay", 3.8, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(76, "Konstantine", "Cristofaro", 5.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(41, "Pierson", "Hartwell", 3.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(42, "Bernardina", "McGowing", 4.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(42, "Bernardina", "McGowing", 5.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(43, "Geoffrey", "Binham", 2.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(44, "Gerri", "Summergill", 3.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 3.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 4.5, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(45, "Randie", "Vlasenkov", 4.6, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(46, "Vincenz", "Comins", 4.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(47, "Gelya", "Haryngton", 2.5, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(47, "Gelya", "Haryngton", 3.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(48, "Misty", "Haquin", 4.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(49, "Ariana", "Hallgate", 3.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(49, "Ariana", "Hallgate", 5.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(50, "Ayn", "Ryder", 1.1, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(50, "Ayn", "Ryder", 2.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(53, "Bellina", "Bortol", 4.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(53, "Bellina", "Bortol", 5.1, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(54, "Aldin", "Haigh", 3.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(55, "Rois", "Slocum", 4.5, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(55, "Rois", "Slocum", 4.2, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(56, "Juanita", "Clapshaw", 3.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(57, "Hedwiga", "Champniss", 4.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(58, "Zaria", "Cleeves", 3.2, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(58, "Zaria", "Cleeves", 4.4, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(59, "Wandie", "Alonso", 5.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 5.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 4.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(60, "Alena", "Eykel", 2.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(61, "Karmen", "Levis", 4.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(61, "Karmen", "Levis", 2.2, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(62, "Rhys", "Kenyon", 2.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(62, "Rhys", "Kenyon", 3.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 3.2, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 4.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(63, "Briana", "Rubinov", 4.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(64, "Gae", "Dellenbrook", 2.0, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(64, "Gae", "Dellenbrook", 3.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 4.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 2.7, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(65, "Whitney", "Raisbeck", 4.0, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 5.1, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 3.3, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(66, "Randa", "Sanchez", 4.4, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 1.9, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 3.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(67, "Joletta", "Kiley", 4.3, "Contabilidad III", 2, "Contabilidad"));
        entidades.add(new Entidad(68, "Alena", "Puttergill", 6.6, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(68, "Alena", "Puttergill", 5.0, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(69, "Corrina", "Gogay", 3.7, "Contabilidad I", 2, "Contabilidad"));
        entidades.add(new Entidad(70, "Fianna", "Tabb", 4.9, "Contabilidad II", 2, "Contabilidad"));
        entidades.add(new Entidad(71, "Marcile", "Dudden", 3.3, "Introducción al Diseño", 3, "Diseño Gráfico"));
        entidades.add(new Entidad(73, "Noemi", "Dunston", 3.7, "Diseño I", 3, "Diseño Gráfico"));
        entidades.add(new Entidad(73, "Noemi", "Dunston", 4.2, "Introducción al Diseño", 3, "Diseño Gráfico"));
        entidades.add(new Entidad(75, "Hana", "Ramsay", 4.0, "Diseño 3D", 3, "Diseño Gráfico"));
    }

    public List<Entidad> getEntidades() {
        return entidades;
    }
}
